## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'amplitude'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_amplitude' #to modify
description = 'Set of PyMoDAQ plugins for Amplitude Systems Lasers'

author = 'Sébastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pyserial', 'crcmod']
##